version: "3.8"

services:
  <SERVICE_NAME>-nginx:
    container_name: <SERVICE_NAME>-nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/acme:/etc/acme.sh
    networks:
      - <NETWORK_NAME>

  <SERVICE_NAME>-letsencrypt:
    container_name: <SERVICE_NAME>-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./nginx/acme:/etc/acme.sh:rw
    networks:
      - <NETWORK_NAME>
    environment:
      DEFAULT_EMAIL: <DEFAULT_EMAIL>

networks:
  <NETWORK_NAME>:
    external: true
